<a href="https://colab.research.google.com/github/ozturkcemal/SupplyChainAnalytics/blob/main/03_FacilityLocation_CenterOfGravity/01_SetCovering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pandas openpyxl

In [30]:
from google.colab import files
uploaded = files.upload()

Saving input.xlsx to input.xlsx


In [49]:
import pandas as pd

# Read the data from the Excel file, specifying the correct header row
df = pd.read_excel('input.xlsx', header=1)  # This assumes the second row (index 1) is your header

# Drop the 'Sites' column, as requested
df = df.loc[:, df.columns != 'Sites']

# Print the cleaned dataframe
print(df.to_string())

   1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
0  0  1  1  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0   0   0
1  1  1  0  0  0  1  1  0  0   0   0   0   0   0   0   0   0   0   0   0
2  0  0  1  1  1  0  0  1  0   0   0   0   0   0   0   0   0   0   0   0
3  0  0  0  0  0  0  1  1  0   1   1   1   1   0   0   0   0   0   0   0
4  0  0  0  0  0  0  0  0  0   0   1   1   1   0   0   1   1   0   0   0
5  0  0  0  0  0  0  0  0  0   1   0   1   0   0   1   1   0   0   0   0
6  0  0  0  0  0  0  0  0  0   0   0   0   1   0   0   0   1   0   0   0
7  0  0  0  0  0  0  0  0  1   0   0   0   0   1   0   0   0   1   0   0
8  0  0  0  0  0  0  0  0  0   0   0   0   0   1   1   0   0   1   1   0
9  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   1   0   1   1


In [55]:
# Create a list 'sites' with numbers from 0 to the number of rows in the dataframe
sites = list(range(0, len(df)))
# Print the list 'sites' to verify
print("sites",sites)
# Create a list 'districts' with numbers from 0 to the number of columns in the dataframe
districts = list(range(0, len(df.columns)))
# Print the list 'districts' to verify
print("districts:",districts)
# Export the dataframe to a CSV file and open it in an editor
#df.to_csv('output.csv')

sites [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
districts: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


In [57]:
import numpy as np

# Create the 'cover' array with the same shape as the dataframe
cover = np.zeros((len(sites), len(districts)), dtype=int)

# Iterate through the dataframe to fill the 'cover' array
for i in range(len(sites)):
    for j in range(len(districts)):
        cover[i][j] = df.iloc[i, j]  # Get the value from the dataframe and assign it to the cover array

# Print the 'cover' array to verify
print("cover array:")
print(cover)

cover array:
[[0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 1 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 0 1 1 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 1 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 1 0 0 1 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1]]


In [58]:
!pip install -q pyomo

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.3/13.3 MB 82.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.6/49.6 kB 3.8 MB/s eta 0:00:00


In [59]:
!apt-get install -y -qq coinor-cbc

Selecting previously unselected package coinor-libcoinutils3v5:amd64.
(Reading database ... 123623 files and directories currently installed.)
Preparing to unpack .../0-coinor-libcoinutils3v5_2.11.4+repack1-2_amd64.deb ...
Unpacking coinor-libcoinutils3v5:amd64 (2.11.4+repack1-2) ...
Selecting previously unselected package coinor-libosi1v5:amd64.
Preparing to unpack .../1-coinor-libosi1v5_0.108.6+repack1-2_amd64.deb ...
Unpacking coinor-libosi1v5:amd64 (0.108.6+repack1-2) ...
Selecting previously unselected package coinor-libclp1.
Preparing to unpack .../2-coinor-libclp1_1.17.5+repack1-1_amd64.deb ...
Unpacking coinor-libclp1 (1.17.5+repack1-1) ...
Selecting previously unselected package coinor-libcgl1:amd64.
Preparing to unpack .../3-coinor-libcgl1_0.60.3+repack1-3_amd64.deb ...
Unpacking coinor-libcgl1:amd64 (0.60.3+repack1-3) ...
Selecting previously unselected package coinor-libcbc3:amd64.
Preparing to unpack .../4-coinor-libcbc3_2.10.7+ds1-1_amd64.deb ...
Unpacking coinor-libcbc3:

In [60]:
import pyomo.environ as pyo

In [62]:
model = pyo.ConcreteModel()

In [63]:
model.x = pyo.Var(sites, within=pyo.Binary)
model.x.pprint()

x : Size=10, Index={0, 1, 2, 3, 4, 5, 6, 7, 8, 9}
    Key : Lower : Value : Upper : Fixed : Stale : Domain
      0 :     0 :  None :     1 : False :  True : Binary
      1 :     0 :  None :     1 : False :  True : Binary
      2 :     0 :  None :     1 : False :  True : Binary
      3 :     0 :  None :     1 : False :  True : Binary
      4 :     0 :  None :     1 : False :  True : Binary
      5 :     0 :  None :     1 : False :  True : Binary
      6 :     0 :  None :     1 : False :  True : Binary
      7 :     0 :  None :     1 : False :  True : Binary
      8 :     0 :  None :     1 : False :  True : Binary
      9 :     0 :  None :     1 : False :  True : Binary


In [64]:
model.obj = pyo.Objective(
    expr = sum(model.x[i] for i in sites),
    sense = pyo.minimize )

model.obj.pprint()

obj : Size=1, Index=None, Active=True
    Key  : Active : Sense    : Expression
    None :   True : minimize : x[0] + x[1] + x[2] + x[3] + x[4] + x[5] + x[6] + x[7] + x[8] + x[9]


In [66]:
model.constraint_coverage = pyo.ConstraintList()
for j in districts:
  model.constraint_coverage.add(sum(model.x[i] for i in sites if cover[i][j]>0) >=1)
model.constraint_coverage.pprint()

This is usually indicative of a modelling error.
To avoid this warning, use block.del_component() and block.add_component().


constraint_coverage : Size=20, Index={1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20}, Active=True
    Key : Lower : Body               : Upper : Active
      1 :   1.0 :               x[1] :  +Inf :   True
      2 :   1.0 :        x[0] + x[1] :  +Inf :   True
      3 :   1.0 :        x[0] + x[2] :  +Inf :   True
      4 :   1.0 :               x[2] :  +Inf :   True
      5 :   1.0 :               x[2] :  +Inf :   True
      6 :   1.0 :               x[1] :  +Inf :   True
      7 :   1.0 :        x[1] + x[3] :  +Inf :   True
      8 :   1.0 :        x[2] + x[3] :  +Inf :   True
      9 :   1.0 :               x[7] :  +Inf :   True
     10 :   1.0 :        x[3] + x[5] :  +Inf :   True
     11 :   1.0 :        x[3] + x[4] :  +Inf :   True
     12 :   1.0 : x[3] + x[4] + x[5] :  +Inf :   True
     13 :   1.0 : x[3] + x[4] + x[6] :  +Inf :   True
     14 :   1.0 :        x[7] + x[8] :  +Inf :   True
     15 :   1.0 :        x[5] + x[8] :  +Inf :   True
     16 :   1.

In [67]:
opt = pyo.SolverFactory('cbc')
model.pprint()

1 Var Declarations
    x : Size=10, Index={0, 1, 2, 3, 4, 5, 6, 7, 8, 9}
        Key : Lower : Value : Upper : Fixed : Stale : Domain
          0 :     0 :  None :     1 : False :  True : Binary
          1 :     0 :  None :     1 : False :  True : Binary
          2 :     0 :  None :     1 : False :  True : Binary
          3 :     0 :  None :     1 : False :  True : Binary
          4 :     0 :  None :     1 : False :  True : Binary
          5 :     0 :  None :     1 : False :  True : Binary
          6 :     0 :  None :     1 : False :  True : Binary
          7 :     0 :  None :     1 : False :  True : Binary
          8 :     0 :  None :     1 : False :  True : Binary
          9 :     0 :  None :     1 : False :  True : Binary

1 Objective Declarations
    obj : Size=1, Index=None, Active=True
        Key  : Active : Sense    : Expression
        None :   True : minimize : x[0] + x[1] + x[2] + x[3] + x[4] + x[5] + x[6] + x[7] + x[8] + x[9]

1 Constraint Declarations
    constrai

In [68]:
opt_solution = opt.solve(model)

In [70]:
# Print the values of the decision variables
print("\nEMS sites opening:")
for i in sites:
    print(f"{i}: {model.x[i].value}")

print(f"Total number of sites: {model.obj()}")


EMS sites opening:
0: 0.0
1: 1.0
2: 1.0
3: 1.0
4: 0.0
5: 1.0
6: 0.0
7: 1.0
8: 0.0
9: 1.0
Total number of sites: 6.0
